### ISSUE TITLE
Number input integer validation does not work as expected

### ISSUE THREAD

**Issue by mnahmias** [adobe/aem-core-forms-components#1144]
### Expected Behaviour
Number Input with Number Type set to Integer should have the same validation behavior as other aem core form inputs.

### Actual Behaviour
In Integer mode, the required validation only works if the user puts a number in the field, clicks off the field, removes the number from the field, and clicks off the field again.

#### Steps to Reproduce
1. Author a Number Input
2. Set the Number Type to Integer
3. Make the field required
4. Author a submit button
5. Preview and submit the form

#### AEM Version (mention the exact version in case of cloud SDK)
2023.12.14697.20231215T125030Z-231200

#### AEM Forms Version
2023.10.25.00-231200

**Comment by rismehta** [comment]
@mnahmias The issue was resolved within release (3.0.2) at https://github.com/adobe/aem-core-forms-components/releases/tag/core-forms-components-reactor-3.0.2. For further details, you may refer to the accompanying release notes.

**Comment by mnahmias** [comment]
Thanks!
