### ISSUE TITLE
Adaptive form fragment responsive grid not respected when linked from fragment component

### ISSUE THREAD

**Issue by tpedrazar** [adobe/aem-core-forms-components#1219]
### Expected Behaviour
Adaptive form fragment responsive grid layout should be respected when linked from a fragment component

### Actual Behaviour
Individual form fields within the fragment fill the width of the fragment container

#### Steps to Reproduce

1. Create and edit a new adaptive form fragment
2. Add at least 1 field into the guide container
3. In Layout mode, make the new field within the container shorter in width (11 columns or less)
4. Return to the forms and documents AEM page and create a new adaptive form
5. Add an adaptive form fragment (resource type of 'core/fd/components/form/fragment/v1/fragment' into the guide container)
6. Open the dialog for the adaptive form fragment and point the 'Fragment reference' field to the fragment created in step 1
7. Enter preview mode to see the difference in field layout between the forms from step 1 and 4

#### AEM Version (mention the exact version in case of cloud SDK)
2023.12.14697.20231215T125030Z-231200

#### AEM Forms Version
2023.10.25.00-231200

#### Sample Code that illustrates the problem
The page source for a text input field in the form fragment container from step 1 (core/fd/components/form/fragmentcontainer/v1/fragmentcontainer -> textinput):
`<div class="textinput base aem-GridColumn--default--none aem-GridColumn aem-GridColumn--default--6 aem-GridColumn--offset--default--0">`

The page source for a text input field within a form fragment from step 4 (core/fd/components/form/fragment/v1/fragment):
`<div class="textinput base">`

**Comment by rismehta** [comment]
@tpedrazar Thank you for bringing this to our attention. @sakshi-arora1, could you please investigate whether this is a bug?

**Comment by tpedrazar** [comment]
Looks like this issue was resolved as of [this PR](https://github.com/adobe/aem-core-forms-components/pull/1227), so upgrading my core forms component version to 3.0.24 has fixed this issue for me. Thank you!
