### ISSUE TITLE
Custom Form Submission Output Data for Custom Submit action

### ISSUE THREAD

**Issue by shravanthprasad** [adobe/aem-core-forms-components#1243]
### Expected Behaviour
Should be able to add custom output data for AF submissions
### Actual Behaviour
No Custom Form Submission Output Data
submissionId,redirectUrl,thankYouMessage;
### Reproduce Scenario (including but not limited to)
Create a custom submit action to post data to an endpoint. Pass submission success data to client side
#### Steps to Reproduce
Create a custom submit action to post data to an endpoint. Pass submission success data to client side
#### Platform and Version
AEM 6.5.17, 1.1.27-wcmB004

**Comment by rismehta** [comment]
@shravanthprasad, I assume you are referring to a client-side API for adding custom additional submit metadata during form submission as described in the API documentation: https://developer.adobe.com/experience-cloud/experience-manager-apis/api/stable/forms/. Is that correct?

While we are in the process of developing this client-side API, you can still directly use the HTTP API to include the additional metadata.

**Comment by rismehta** [comment]
In the latest version, we've included support for setting extra custom submit metadata directly from the client side. For a code sample, please refer to this link: [GitHub - Adobe AEM Core Forms Components](https://github.com/adobe/aem-core-forms-components/blob/master/ui.apps/src/main/content/jcr_root/apps/core/fd/components/aemform/v2/aemform/aemform.html#L25-L31).

Closing the issue as resolved. If you have any more questions or need further assistance, please don't hesitate to open a new issue.
