### ISSUE TITLE
Core Component Date Picker Min and Max dates not working

### ISSUE THREAD

**Issue by manu-adobe** [adobe/aem-core-forms-components#1263]
### Expected Behaviour
If Author chooses to set Min and Max dates for e.g. 1 Jun and 30 Jun, then users shouldnt be allowed to choose 31 May or 1 Jul
### Actual Behaviour
In actual, user is able to choose 31 May and date upto 29 Jun
### Reproduce Scenario (including but not limited to)
Reproducible on multiple environment
#### Steps to Reproduce
Set Min and Max dates while Authoring under Validation tab and we are able to choose 31 May and date upto 29 Jun
#### Platform and Version
AEM Cloud Server
#### AEM Version (mention the exact version in case of cloud SDK)
2024.3.15575.20240318T214814Z-231200
#### AEM Forms Version
2023.10.25.00-231200, Forms core component 3.0.28, wcm component version 2.24.6
#### Sample Code that illustrates the problem
NA
#### Logs taken while reproducing problem
NA

**Comment by rismehta** [comment]
@manu-adobe In the date picker widget, dates outside the specified minimum and maximum values are not disabled. Instead, if a user selects a date outside this range, an error message is displayed. 

We have an internal ticket logged to develop a new version of the date picker component with this improvement.

**Comment by manu-adobe** [comment]
> @manu-adobe In the date picker widget, dates outside the specified minimum and maximum values are not disabled. Instead, if a user selects a date outside this range, an error message is displayed.
> 
> We have an internal ticket logged to develop a new version of the date picker component with this improvement.

Problem is when I choose to set min date 1 Jun and Max date 30 Jun and added error messages in validation tab, then I am able to choose 31 May without any errors but error is shown when I choose 30 May. Similarly I cannot choose 30 Jun but upto 29 Jun without error message.

**Comment by rismehta** [comment]
> > @manu-adobe In the date picker widget, dates outside the specified minimum and maximum values are not disabled. Instead, if a user selects a date outside this range, an error message is displayed.
> > We have an internal ticket logged to develop a new version of the date picker component with this improvement.
> 
> Problem is when I choose to set min date 1 Jun and Max date 30 Jun and added error messages in validation tab, then I am able to choose 31 May without any errors but error is shown when I choose 30 May. Similarly I cannot choose 30 Jun but upto 29 Jun without error message.

Thank you for bringing this issue to our attention. It will be resolved soon

**Comment by rismehta** [comment]
@manu-adobe This should be fixed via, https://github.com/adobe/aem-core-forms-components/pull/1270

**Comment by rismehta** [comment]
@manu-adobe This is fixed via, https://github.com/adobe/aem-core-forms-components/releases/tag/core-forms-components-reactor-3.0.34
