### ISSUE TITLE
Translation values not picked up from dictionary

### ISSUE THREAD

**Issue by shravanthprasad** [adobe/aem-core-forms-components#1345]
Link from examples content
http://localhost:4502/content/forms/af/core-components-it/samples/af2-form-translation.html?afAcceptLang=de
AEM version 6.5.20
core forms component version 1.1.38

**Comment by rismehta** [comment]
@shravanthprasad You might have overlooked some translation steps, as this use-case is part of the automation pipeline. Additionally, could you upgrade to the latest core component version compatible with 6.5.20, as specified here: https://github.com/adobe/aem-core-forms-components/blob/release/650/VERSIONS.md?

additionally, you could also refer, https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/forms/adaptive-forms-authoring/authoring-adaptive-forms-core-components/create-an-adaptive-form-on-forms-cs/using-aem-translation-workflow-to-localize-adaptive-forms-core-components

**Comment by shravanthprasad** [comment]
@rismehta 
All the translation steps were followed and this was working fine in older version. Here is a snapshot of the i18n resources on new version(1.1.38) vs old version(1.1.27)
<img width="858" alt="v1 1 27-translationkeyresources" src="https://github.com/user-attachments/assets/f350f9e3-c80e-4d83-b673-fa04d15c28be">
<img width="1033" alt="v1 1 38-translationresourcesnil" src="https://github.com/user-attachments/assets/2ba3ad93-0bae-4083-80af-c9cbc8fe3848">

**Comment by rismehta** [comment]
What are the paths to the dictionary in both the old and new versions?

**Comment by rismehta** [comment]
The issue was caused by missing values in the includedPath property of the Apache Sling I18N Resource Bundle Provider (org.apache.sling.i18n.impl.JcrResourceBundleProvider). Specifically, the values /content/forms/af and /content/dam/formsanddocuments were not included due to the in-place upgrade.

**Comment by shravanthprasad** [comment]
Appreciate your quick support @rismehta
