### ISSUE TITLE
Guidance for horizontal component alignment 

### ISSUE THREAD

**Issue by richardwegier** [adobe/aem-core-forms-components#1352]
### Expected Behaviour
The editor has the possibility to decide which components should be displayed side-by-side (horizontally) for the desktop view of an Adaptive Form.

### Actual Behaviour
We are currently not certain on how to achieve the horizontal display of components in desktop view as we did not find any conclusive documentation. Please let us know if there is any documentation for guidance. Earlier there was the possibility to configure a panel with a number of columns.

#### AEM Version (mention the exact version in case of cloud SDK)
6.5 SP21

#### AEM Forms Version
- AF version: 6.5 SP21
- AEM Core Components version: 1.1.50

**Comment by rismehta** [comment]
@richardwegier You can use the layout layer in the form editor to arrange components side by side (i.e., horizontally). I’ve attached a screenshot for your reference.

<img width="1519" alt="Screenshot 2024-08-13 at 2 21 17 PM" src="https://github.com/user-attachments/assets/6a4f4aa9-61af-4fc2-832a-ce45f8292e69">
