### ISSUE TITLE
Content not getting saved when using RTE full screen option on forms core components help content tab

### ISSUE THREAD

**Issue by ckokildel** [adobe/aem-core-forms-components#1482]
### Expected Behaviour
When editing any core forms component there is a help tab in the dialog that is used to author short description and help text. The content authored in any of these should get saved and shown on the form markup.
The authoring can be done in the input field directly or using the full screen option on the RTE.

<img width="257" alt="image" src="https://github.com/user-attachments/assets/3421b8a5-435f-4f4a-8bca-f782d5ba6175">

<img width="257" alt="image" src="https://github.com/user-attachments/assets/4ff40933-2bc1-47ee-aaa5-e8124ee1459d">

<img width="671" alt="image" src="https://github.com/user-attachments/assets/11700d26-4426-4960-b591-eae11f90ccdd">

### Actual Behaviour
When the component dialog opens and the short description or help text is directly authored in the input field the added content is saved and shows up on the form. But when the component dialog is opened and instead of authoring the input field, the full screen option is clicked and the content is authored then the content is not saved and when the component dialog is opened again then the old content is seen.

### Reproduce Scenario (including but not limited to)
This can be observed in core components version above 
<core.wcm.components.version>2.24.6</core.wcm.components.version>
<core.forms.components.version>3.0.54</core.forms.components.version>
<core.forms.components.af.version>3.0.54</core.forms.components.af.version>

I have tried using following setup on local and was able to reproduce the issue.
- Project archetypeVersion=51
- sdkFormsVersion=2024.10.23.06-241000
- AEM sdkVersion=2024.11.18598.20241113T125352Z-241000
- Core components version = 3.0.72
- Core WCM components version = 2.24.6

#### Steps to Reproduce

1. Add any core component to a new form. In my case I had added radio component.
<img width="677" alt="image" src="https://github.com/user-attachments/assets/80057d40-5872-4c62-880a-9c4888c188d1">

2. Author the short description and help text without using full screen option. Click on Done. The authored content will be seen on the form.
<img width="284" alt="image" src="https://github.com/user-attachments/assets/b436a8a8-abbf-4740-9ee2-4106dc96d94d">

<img width="577" alt="image" src="https://github.com/user-attachments/assets/5899089d-4caa-46f9-b613-1ea7fc244ab2">

3. Re-author the short description and help text using the full screen option directly without editing the input fields of these. Click on Done. The newly authored content using the full screen option directly is not visible on the form and still the old content is visible.

<img width="284" alt="image" src="https://github.com/user-attachments/assets/ce4ff151-1681-488f-9719-6f12c98de54c">

<img width="688" alt="image" src="https://github.com/user-attachments/assets/b21903d4-f1dc-4399-a0d4-bde1767fb4c3">

<img width="675" alt="image" src="https://github.com/user-attachments/assets/0ddba968-31ef-4fd3-9a8b-fe41bee27af5">

<img width="311" alt="image" src="https://github.com/user-attachments/assets/8b27646b-37a7-41b7-9e7b-7543358b6627">

<img width="599" alt="image" src="https://github.com/user-attachments/assets/c1dfb365-ff9d-49b8-9991-9e88561172f4">

#### Platform and Version
AEM cloud environments and AEM cloud SDK

#### AEM Version (mention the exact version in case of cloud SDK)
AEM sdkVersion=2024.11.18598.20241113T125352Z-241000

#### AEM Forms Version
2024.10.23.06-241000

#### Sample Code that illustrates the problem
Content authoring as described above.

**Comment by rismehta** [comment]
@im-shiv  Could you please check this ?

**Comment by im-shiv** [comment]
@rismehta It's a RTE editor bug, I am looking into it, whether it can be solver at our side, or do we need to log a ticket for the respective team

**Comment by im-shiv** [comment]
@rismehta bug is on RTE editor side. We have an internal issue created for this.
@ckokildel if it is a blocker, please get it raised through customer support channel.
