### ISSUE TITLE
Need to overlay aem form text input and button

### ISSUE THREAD

**Issue by pawee-del** [adobe/aem-core-forms-components#48]
### Expected Behaviour
I need to overlay aem form text input and button, however adobe support suggest to use aem core form components. We already integrated aem forms into aem sites, so what is this aem core form components? 
#### Logs taken while reproducing problem

**Comment by pankaj-parashar** [comment]
@pawee-del What is AEM Forms Version you are using? AEM Forms core components have only form container component as of now - https://aemcomponents.dev/content/core-components-examples/library/page-authoring/aemform.html. I believe you are using this core component. Foundation AEM Forms Container component which comes with AEM Forms deployment has been deprecated. AFAIK, there is no forms core components available for text input and button as of now, only foundation components are available within AEM Forms for the same.

What is your use case? If you want to achieve custom appearance, please refer documentation - https://experienceleague.adobe.com/docs/experience-manager-65/forms/customize-aem-forms/custom-appearance-widget-adaptive-form.html?lang=en
cc : @rismehta

**Comment by pawee-del** [comment]
i wanna customise the rte plugins for aem form text input and also changes styles on the aem form button. For button i have add css in the configure css field of the aem form button but it screws up the css, hence why i am thinking of overlay widget.jsp in the aem form button.

but the show stopper isnt the above its when building the package, if i have /app/fd/af in my filter.xml, the aem jackrabbit validator failed with an error

**Comment by rismehta** [comment]
> AFAIK, there is no forms core components available for text input and button as of now, only foundation components are available within AEM Forms for the same.

Core components for other form components would be available soon. The current implementation should make use of foundation components

**Comment by rismehta** [comment]
> but the show stopper isnt the above its when building the package, if i have /app/fd/af in my filter.xml, the aem jackrabbit validator failed with an error

you can overlay existing foundation components present at /apps/fd/af/components.

**Comment by pawee-del** [comment]
when i overlay it in this way, see pic , the error got thrown
![Greenshot 2022-02-18 07 47 54](https://user-images.githubusercontent.com/72118587/154568377-0c154069-754b-46e8-8af5-125796fcd2fa.png)
![Greenshot 2022-02-18 07 47 37](https://user-images.githubusercontent.com/72118587/154568386-6002cb77-4571-4497-9e42-41f585ede112.png)

error log :
`[INFO] Using 10 validators for package of type APPLICATION: jackrabbit-accesscontrol (org.apache.jackrabbit.vault.validation.spi.impl.AccessControlValidator), jackrabbit-filter (org.apache.jackrabbit.vault.validation.spi.impl.AdvancedFilterValidator), jackrabbit-properties (org.apache.jackrabbit.vault.validation.spi.impl.AdvancedPropertiesValidator), jackrabbit-docviewparser (org.apache.jackrabbit.vault.validation.spi.impl.DocumentViewParserValidator), jackrabbit-dependencies (org.apache.jackrabbit.vault.validation.spi.impl.DependencyValidator), jackrabbit-emptyelements (org.apache.jackrabbit.vault.validation.spi.impl.EmptyElementsValidator), jackrabbit-mergelimitations (org.apache.jackrabbit.vault.validation.spi.impl.MergeLimitationsValidator), jackrabbit-oakindex (org.apache.jackrabbit.vault.validation.spi.impl.OakIndexDefinitionValidator), jackrabbit-packagetype (org.apache.jackrabbit.vault.validation.spi.impl.PackageTypeValidator), jackrabbit-nodetypes (org.apache.jackrabbit.vault.validation.spi.impl.nodetype.NodeTypeValidator)
[ERROR] ValidationViolation: "jackrabbit-filter: Filter root's ancestor '/apps/fd/af' is not covered by any of the specified dependencies nor a valid root.", filePath=META-INF/vault/filter.xml
[INFO] ValidationViolation: "jackrabbit-docviewparser: This file is not detected as docview xml file and therefore treated as binary", filePath=jcr_root/apps/cq/xssprotection/config.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Maurice Blackburn Commons 0.0.1-SNAPSHOT:
[INFO] 
[INFO] Maurice Blackburn Commons .......................... SUCCESS [  0.399 s]
[INFO] Maurice Blackburn Commons - Core ................... SUCCESS [ 19.710 s]
[INFO] Maurice Blackburn Commons - UI Frontend ............ SUCCESS [ 35.110 s]
[INFO] Maurice Blackburn Commons - Repository Structure Package SUCCESS [  1.290 s]
[INFO] Maurice Blackburn Commons - UI apps ................ FAILURE [ 10.868 s]
[INFO] Maurice Blackburn Commons - UI content ............. SKIPPED
[INFO] Maurice Blackburn Commons - UI config .............. SKIPPED
[INFO] Maurice Blackburn Commons - All .................... SKIPPED
[INFO] Maurice Blackburn Commons - Integration Tests ...... SKIPPED
[INFO] Maurice Blackburn Commons - UI Tests ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:10 min
[INFO] Finished at: 2022-02-18T07:44:56+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.jackrabbit:filevault-package-maven-plugin:1.1.6:validate-package (default-validate-package) on project mbl-commons.ui.apps: Found 1 violation(s) (with severity=ERROR). Check above errors for details -> [Help 1]
[ERROR] `

**Comment by virresh** [comment]
@pawee-del pls have a look at https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/developing/repository-structure-package.html?lang=en#errors-and-debugging

You're likely missing entries from your repository structure.
Hope this helps.

**Comment by pawee-del** [comment]
Ok lets close this ticket for now i managed to repsolve it
