### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npm when deploying on AEM Cloud Service ci/cd pipeline

### ISSUE THREAD

**Issue by tonijhanel** [adobe/aem-core-forms-components#506]
### Expected Behaviour
Successful build when deploying AEM Cloud Service ci/cd pipeline
### Actual Behaviour
Build failing at build & Unit Testing step
### Reproduce Scenario (including but not limited to)
Tried running several times
#### Steps to Reproduce
Run development pipeline on AEM CS
#### Platform and Version
AEM CS release 2023.1.10912.20230130T173736Z
#### Logs taken while reproducing problem
[build_maven_build (47).log](https://github.com/adobe/aem-core-forms-components/files/10842787/build_maven_build.47.log)

**Comment by nit23uec** [comment]
@tonijhanel , the core components need not be built by the CI/CD pipeline. Instead your project can embed already released core component artifacts. To enable core core components, you may follow:
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/forms/adaptive-forms-authoring/authoring-adaptive-forms-core-components/create-an-adaptive-form-on-forms-cs/creating-adaptive-form-core-components.html?lang=en#pre-requisites
