### ISSUE TITLE
Rule Editor Not Working in Forms Core Components Examples

### ISSUE THREAD

**Issue by vabs95** [adobe/aem-core-forms-components#552]
### Expected Behaviour
Rules Editor should open without any issues.

### Actual Behaviour
Rules Editor is breaking due to JS error.

![Screenshot 2023-03-29 at 23 11 28](https://user-images.githubusercontent.com/17997879/228668642-bd973b70-c10d-43cd-8445-02018aa082bd.png)
![Screenshot 2023-03-29 at 23 11 38](https://user-images.githubusercontent.com/17997879/228668687-9a769c12-5804-405d-ae47-99a5d8821515.png)

#### Steps to Reproduce

1. Open any Form Core Component Example Page in author mode.
2. Select the Form Core Component and open Rules Editor.
3. Rules Editor UI is stuck. Unable to create/close editor.

#### Platform and Version
AEM SDK : 2023.3.11382.20230315T073850Z-230100
AEM Forms SDK: 2023.02.01.00-230100
AEM Forms Core: 2.0.8

#### Cause

1.  The issue is caused by the Demo Container Component which wrapping the Forms Core Component.
 `forms-components-examples/components/demo/component`
2. If you remove it, the Rules Editor starts working. 
![Screenshot 2023-03-29 at 23 19 45](https://user-images.githubusercontent.com/17997879/228670340-c4f82ad6-c31c-4898-b18e-f27a62172dd8.png)

**Comment by vabs95** [comment]
@barshat7 These changes were made in this commit: c4146903. Can you please check and confirm.

**Comment by rismehta** [comment]
@vabs95 Please use the latest release of core components `2.0.14`

**Comment by rismehta** [comment]
Test PR: https://github.com/adobe/aem-core-forms-components/pull/574

**Comment by rismehta** [comment]
The issue is fixed.
