### ISSUE TITLE
How to add a fragment to the form using core components?

### ISSUE THREAD

**Issue by notkksm** [adobe/aem-core-forms-components#908]
When we create a form using core page component (core/fd/components/page/v1/page), it's not possible to add a fragment to the form using core components. We can only add a fragment using OOTB Panel. Could you please tell if it is possible to add a fragment to the form using only core components?
We use AEM 6.5.18, adobe-aem-forms-addon-6.5.18, aem-service-pkg-6.5.18, core.forms.components 1.1.24

**Comment by sakshi-arora1** [comment]
This support is added in AEM 6.5.19, core.forms.components 1.1.32
