### ISSUE TITLE
Send input data in UTF-8

### ISSUE THREAD

**Issue by IgorIvanovGrodno** [adobe/aem-core-forms-components#970]
We created an adaptive form using core components. We configured a guide container submission like 'Submit to REST endpoint'. When a user fills a form and submits it using german or another language, our servlet recieves incorrect data.
For instanse:
" Adres�t " instead of " Adresát " 
As far as I know, there are OOTB intermediate services which handle input data. How can we configure them to use UTF-8 coding?
We tried configured our submission to 'Invoke an AEM workflow' - we get correct data.

**Comment by rismehta** [comment]
@IgorIvanovGrodno I presume that this issue has been resolved, as it was recently addressed as part of the product's updates.
