### ISSUE TITLE
AEM Core Forms component usage on 6.5

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aem-core-forms-components#988]
Could you please provide a documentation on how to install AEM Forms Core Components on AEM 6.5?

After installing the latest released version, the bundles do not start, see screenshot for the missing packages. On the other hand it states in the docs for AEM 6.5.17 that it is now possible to use the AEM Page Editor, where it mentions these core components to do this. (see https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/6.5.17.html?lang=en)

![Screenshot 2023-11-06 at 16 27 20](https://github.com/adobe/aem-core-forms-components/assets/4967758/ca228fe8-8091-43ac-8697-edffce989e79)

**Comment by rismehta** [comment]
@royteeuwen The problem arises when you install an incompatible version of the core component in AEM 6.5. Please verify the compatibility version matrix available [here](https://github.com/adobe/aem-core-forms-components/blob/release/650/VERSIONS.md)

Furthermore, I have requested the documentation team to incorporate these details into the document link you provided.
